// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAADxUtoN-c0meP-eIQa_Sv50lh0u2fQwc',
    appId: '1:37225093755:web:ebebfca5eaa9174f27a0de',
    messagingSenderId: '37225093755',
    projectId: 'synergy-38bc6',
    authDomain: 'synergy-38bc6.firebaseapp.com',
    storageBucket: 'synergy-38bc6.firebasestorage.app',
    measurementId: 'G-LC6DZ9708Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_oIEXD-DzVD2j8h1qsuozxvjc8eXVSjI',
    appId: '1:37225093755:android:7219b83355b92d3527a0de',
    messagingSenderId: '37225093755',
    projectId: 'synergy-38bc6',
    storageBucket: 'synergy-38bc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSPjPV_i81b4BqGCEEWqp-Wk06LSaoMd8',
    appId: '1:37225093755:ios:f6a067ea50d979eb27a0de',
    messagingSenderId: '37225093755',
    projectId: 'synergy-38bc6',
    storageBucket: 'synergy-38bc6.firebasestorage.app',
    iosBundleId: 'com.impal.gabungyuk',
  );
}
